import { ArrowUpRight, ArrowRight, Database, Boxes, Workflow, Activity, Globe2, ChevronRight, BookOpen, Code2, Cpu } from 'lucide-react';

const modules = [
  {id:'hub', n:'01', title:'AI Hub', sub:'데이터에서 모델까지, 하나의 자산으로.', desc:'데이터셋 · 모델 · Notebook', icon:Database, color:'blue', tags:['Dataset','Model','Code']},
  {id:'training', n:'02', title:'Training', sub:'아이디어를 실행 가능한 모델로.', desc:'학습 실행 · 실험 관리 · 평가', icon:Workflow, color:'purple', tags:['Notebook','Experiment']},
  {id:'deployment', n:'03', title:'Deployment', sub:'검증된 모델을 생산 현장으로.', desc:'모델 배포 · 버전 관리 · 확산', icon:Boxes, color:'cyan', tags:['Release','Rollout']},
  {id:'monitoring', n:'04', title:'Monitoring', sub:'현장의 변화를, 다음 학습으로.', desc:'운영 현황 · 성능 추적 · Drift', icon:Activity, color:'green', tags:['Performance','Drift']},
];
export default function Home(){return <div className="portal">
  <header className="header"><a href="#" aria-label="PRIZM 홈" className="brand"><img src="/prizm-logo.svg" alt="PRIZM"/><span className="brand-divider"/><span className="brand-label">MANUFACTURING AI</span></a><nav aria-label="주 메뉴"><a className="active" href="#">Overview</a>{modules.map(m=><a key={m.id} href={'#'+m.id}>{m.title}</a>)}</nav><div className="header-end"><span className="preview">DESIGN PREVIEW</span><span className="hyundai">HYUNDAI</span></div></header>
  <main>
  <section className="hero" aria-labelledby="hero-title"><img className="world" src="/prizm-network.png" alt="스펙트럼 빛으로 연결되는 글로벌 제조 공장 네트워크"/><div className="hero-shade"/><div className="hero-inner"><div className="eyebrow"><span/> THE MANUFACTURING AI PLATFORM</div><h1 id="hero-title">Production-ready<br/>intelligence.<br/><span className="muted-title">Zero-loss manufacturing.</span></h1><p className="hero-ko">데이터의 가능성을, 모든 공장의 지능으로.</p><a className="hero-link" href="#workspace">워크스페이스 둘러보기 <ArrowRight size={18}/></a><div className="hero-bottom"><span className="line"/><span>ONE PLATFORM. EVERY FACTORY.</span></div></div><div className="image-caption"><Globe2 size={15}/><span>CONNECTED INTELLIGENCE</span><i/></div></section>
  <section className="workspace" id="workspace"><div className="section-top"><div><div className="section-kicker">YOUR WORKSPACE</div><h2>제조 AI의 모든 여정, PRIZM에서.</h2></div><span className="journey">BUILD <ChevronRight/> OPERATE <ChevronRight/> EVOLVE</span></div><div className="module-grid">{modules.map(m=><article id={m.id} key={m.id} className={'module '+m.color} tabIndex={0}><div className="module-top"><span className="module-icon"><m.icon size={23} strokeWidth={1.6}/></span><span className="module-number">{m.n}</span></div><div className="module-title"><h3>{m.title}</h3><ArrowUpRight size={23}/></div><p className="module-sub">{m.sub}</p><p className="module-desc">{m.desc}</p><div className="module-tags">{m.tags.map(t=><span key={t}>{t}</span>)}</div></article>)}</div>
  <div className="resource-strip"><div className="resource-title"><BookOpen size={21}/><div><strong>처음 시작하시나요?</strong><p>표준 가이드와 함께 시작하세요.</p></div></div><div className="resource-item"><Code2 size={18}/><span>Notebook 작성 가이드</span><span className="soon">준비 중</span></div><div className="resource-item"><Database size={18}/><span>AI 자산 등록 가이드</span><span className="soon">준비 중</span></div><div className="resource-item"><Cpu size={18}/><span>Runtime 사용 가이드</span><span className="soon">준비 중</span></div></div>
  </section></main><footer><div><img src="/prizm-icon.png" alt=""/><span>PRIZM</span><span className="footer-line"/>Production-ready Intelligence for Zero-loss Manufacturing</div><span>HYUNDAI MOTOR COMPANY <span className="copyright">© 2026</span></span></footer>
</div>}
